services:
  nginx:
    image: nginx
    container_name: mon-serveur-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - monitoring
    depends_on:
      - ghost

  ghost:
    image: ghost:5
    container_name: ghost
    restart: always
    environment:
      url: https://bafix.duckdns.org
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    volumes:
      - ghost-data:/var/lib/ghost/content
    networks:
      - monitoring

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - uptime-kuma:/app/data
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  ghost-data:
  uptime-kuma:
